/**
 * _redirects generator (Task 3.2) — the phased-cutover mechanism.
 *
 * Reads migration/manifest.json and emits public/_redirects:
 * - every OLD Ghost URL keeps working (spec §4 hard constraint):
 *   migrated post -> 301 into /zh/writing/<slug>/,
 *   pending post  -> 200-proxy to the still-running Ghost origin.
 * The proxy list SHRINKS post-by-post as parity gates pass — that's the
 * "drain" in the phased cutover.
 */
import fs from 'node:fs';
import path from 'node:path';

export function genRedirects(manifest, ghostOrigin) {
  const lines = [
    '# GENERATED by scripts/redirects/gen.mjs — do not edit by hand.',
    '# Old Ghost URLs: 301 when migrated, proxy-to-ghost while pending.',
  ];
  for (const p of manifest.posts) {
    if (p.migrated) {
      lines.push(`/${p.slug}/ /zh/writing/${p.slug}/ 301`);
      lines.push(`/${p.slug} /zh/writing/${p.slug}/ 301`);
    } else {
      lines.push(`/${p.slug}/ ${ghostOrigin}/${p.slug}/ 200`);
      lines.push(`/${p.slug} ${ghostOrigin}/${p.slug}/ 200`);
    }
  }
  lines.push(
    manifest.aboutMigrated ? '/about/ /zh/about/ 301' : `/about/ ${ghostOrigin}/about/ 200`,
  );
  lines.push(manifest.rssMigrated ? '/rss/ /rss.xml 301' : `/rss/ ${ghostOrigin}/rss/ 200`);
  if (!manifest.imagesLocal) {
    lines.push(`/content/images/* ${ghostOrigin}/content/images/:splat 200`);
  }
  return lines.join('\n') + '\n';
}

const isMain = process.argv[1] && path.basename(process.argv[1]) === 'gen.mjs';
if (isMain) {
  const repo = process.cwd();
  const manifest = JSON.parse(fs.readFileSync(path.join(repo, 'migration/manifest.json'), 'utf8'));
  const ghostOrigin = manifest.ghostOrigin ?? 'https://ghost-origin.timeobserver137.cyou';
  const out = genRedirects(manifest, ghostOrigin);
  fs.writeFileSync(path.join(repo, 'public/_redirects'), out, 'utf8');
  const n301 = (out.match(/ 301$/gm) ?? []).length;
  const n200 = (out.match(/ 200$/gm) ?? []).length;
  console.log(`public/_redirects written: ${n301} redirects, ${n200} proxy lines`);
}
